### ISSUE TITLE
`AEOTPTextField` dependency were found

### ISSUE THREAD

**Issue by appsgeek** [AbdelrhmanKamalEliwa/AEOTPTextField#10]
Specs satisfying the `AEOTPTextField` dependency were found, but they required a higher minimum deployment target.
I set 12.0 for Project deployment and Target deployment

**Comment by AbdelrhmanKamalEliwa** [comment]
Yes, you should set the minimum deployment target to 13 in this version. but you can downgrade to an older version that works with deployment target 12.
