### ISSUE TITLE
Margin or padding for each text field !

### ISSUE THREAD

**Issue by wonder2011** [AbdelrhmanKamalEliwa/AEOTPTextField#11]
Awesome library, I use this intensively not only for OTP. But I need some level of customization for become more usable to other thinks. For example I need tf 1 & 2 to stay more closer, and 3 & 4 more closer and with a margin of 20 px for example with 1 & 2.

This for example: --  --  --

How I can achieve this ?

**Comment by AbdelrhmanKamalEliwa** [comment]
@wonder2011 unfortunately, you can't do that in this version, will make it available in the next release

**Comment by fhernandezKt88** [comment]
@AbdelrhmanKamalEliwa awesome, thanks !
