### ISSUE TITLE
Not getting border when with border textfields until select textfield or enter first number

### ISSUE THREAD

**Issue by raavan199** [AbdelrhmanKamalEliwa/AEOTPTextField#13]

**Comment by AbdelrhmanKamalEliwa** [comment]
You can apply the border by using otpDefaultBorderColor property

**Comment by Ayyarappan** [comment]
`otpTextField.otpDelegate = self
  otpTextField.otpCornerRaduis = 16.13
  otpTextField.otpDefaultBorderColor = UIColor(red: 0.627, green: 0.639, blue: 0.659, alpha: 1)
  otpTextField.otpDefaultBorderWidth = 1.47`
  
  Even after added otpDefaultBorderColor property, still the same issue exists. 🚨🚨
  Only border color set after user starts typing in otpTextField.
  
  ** Mark it as OPEN issue **

**Comment by raavan199** [comment]
@Ayyarappan I solved this issue and requested to merge my commit but he denied it and did not merge my request. let me know if you can not find a solution I will help you to resolve it.

**Comment by media-mind-atul** [comment]
Yes, its not working until you enter first character in the field.

**Comment by Ayyarappan** [comment]
> @Ayyarappan I solved this issue and requested to merge my commit but he denied it and did not merge my request. let me know if you can not find a solution I will help you to resolve it.

thanks @raavan199 for your response. 
Sorry, I moved to another framework which suits my requirements. 

But anyway, you can add your code snippet in comments here. 
It will be useful for someone who experience the same issue ✅

**Comment by media-mind-atul** [comment]
@Ayyarappan Can you please share the other framework which is working as expected?

**Comment by Ayyarappan** [comment]
> @Ayyarappan Can you please share the other framework which is working as expected?

**VPMOTPView**

@media-mind-atul  Try this framework and let me know if you face any issues. 🎉
