### ISSUE TITLE
how to make it auto Fill oneTimeCode (OTP) code type espaecicallly in SwiftUI

### ISSUE THREAD

**Issue by asar-s** [AbdelrhmanKamalEliwa/AEOTPTextField#16]
how make it autFillCode type especially in swiftUI ?

**Comment by AAlboghdady** [comment]
Did you manage to implement this feature?
@asar-s

**Comment by AbdelrhmanKamalEliwa** [comment]
If I understand. It’s already implemented, make sure that the OTP message contains the word “code” and the OTP will appear on the keyboard as a suggestion.

If that not what you need, reply with more details.
