### ISSUE TITLE
Clear Background

### ISSUE THREAD

**Issue by Taimoor20** [AbdelrhmanKamalEliwa/AEOTPTextField#2]
How to set the **clear background** view for the OTP textfield as I could not find any attribute of this library regarding this. If there  is some attribute for this then please do let me know.

**Comment by AbdelrhmanKamalEliwa** [comment]
You can use this line below:

```
otpTextField.otpBackgroundColor = .white
```

**Comment by AbdelrhmanKamalEliwa** [comment]
You can use this line below: 

```
otpTextField.otpBackgroundColor = .clear
```
