### ISSUE TITLE
isSecureTextEntry 

### ISSUE THREAD

**Issue by OmarMohamedFlex** [AbdelrhmanKamalEliwa/AEOTPTextField#3]
isSecureTextEntry isn't working

**Comment by AbdelrhmanKamalEliwa** [comment]
If using the UIKit version, just set the isSecureTextEntry property to True.
```
otpTextField.isSecureTextEntry = true
```

And if using the SwiftUI version, just set the isSecureTextEntry property in the init to True.
```
AEOTPView(text: $otp, isSecureTextEntry: true)
```
