### ISSUE TITLE
Not working for 11.0 deployment target

### ISSUE THREAD

**Issue by subhojitc10** [AbdelrhmanKamalEliwa/AEOTPTextField#9]
Can you please check why it's not supporting deployment target 11.0, although you mention it should support 10.0 and higher.
<img width="570" alt="Screenshot 2022-09-14 at 11 12 07 PM" src="https://user-images.githubusercontent.com/51910234/190225331-1e3bd5a1-a7e4-43ef-9976-962f115909b1.png">

**Comment by AbdelrhmanKamalEliwa** [comment]
I'm really sorry bro, It was a mistake with the ReadMe file and it's updated now. Kindly, note that the minimum target number is 12.1 and the Swift version is 5.
